[tool.poetry]
name = "essay-judge"
version = "0.1.0"
description = ""
authors = ["Yen-Ting Li <ytli.tw@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langchain-community = "^0.2.1"
langchain-openai = "^0.1.8"
google-auth-oauthlib = "^1.2.0"
google-api-python-client = "^2.131.0"
google-auth-httplib2 = "^0.2.0"
textract = "^1.6.5"
six = "1.12.0"
matplotlib = "^3.9.0"



[tool.poetry.plugins.dotenv]
ignore = "false"
location = "./private/.env"

[tool.poetry.scripts]
start = "essay_judge.interface:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
